/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as LinkAccountRouteImport } from './routes/link-account';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings';
import { Route as InviteTokenRouteImport } from './routes/invite/$token';
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index';
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id';
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new';
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index';
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings/about';
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account';
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance';
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations';
import { Route as AuthenticatedSettingsRetentionRouteImport } from './routes/_authenticated/settings/retention';
import { Route as AuthenticatedSettingsStorageRouteImport } from './routes/_authenticated/settings/storage';
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team';
import { Route as AuthenticatedSettingsTokensRouteImport } from './routes/_authenticated/settings/tokens';
import { Route as AuthenticatedProjectsIdIndexRouteImport } from './routes/_authenticated/projects/$id/index';
import { Route as AuthenticatedProjectsIdLogsRouteImport } from './routes/_authenticated/projects/$id/logs';
import { Route as AuthenticatedProjectsIdSettingsRouteImport } from './routes/_authenticated/projects/$id/settings';
import { Route as AuthenticatedProjectsIdAgentsIndexRouteImport } from './routes/_authenticated/projects/$id/agents/index';
import { Route as AuthenticatedProjectsIdAgentsTraceIdRouteImport } from './routes/_authenticated/projects/$id/agents/$traceId';
import { Route as AuthenticatedProjectsIdIssuesIndexRouteImport } from './routes/_authenticated/projects/$id/issues/index';
import { Route as AuthenticatedProjectsIdPerformanceIndexRouteImport } from './routes/_authenticated/projects/$id/performance/index';
import { Route as AuthenticatedProjectsIdPerformanceTxnIdRouteImport } from './routes/_authenticated/projects/$id/performance/$txnId';
import { Route as AuthenticatedProjectsIdPerformanceSummaryRouteImport } from './routes/_authenticated/projects/$id/performance/summary';
import { Route as AuthenticatedProjectsIdReleasesIndexRouteImport } from './routes/_authenticated/projects/$id/releases/index';
import { Route as AuthenticatedProjectsIdReleasesReleaseRouteImport } from './routes/_authenticated/projects/$id/releases/$release';
import { Route as AuthenticatedProjectsIdSettingsIndexRouteImport } from './routes/_authenticated/projects/$id/settings/index';
import { Route as AuthenticatedProjectsIdSettingsAlertsRouteImport } from './routes/_authenticated/projects/$id/settings/alerts';
import { Route as AuthenticatedProjectsIdSettingsClientKeysRouteImport } from './routes/_authenticated/projects/$id/settings/client-keys';
import { Route as AuthenticatedProjectsIdSettingsGeneralRouteImport } from './routes/_authenticated/projects/$id/settings/general';
import { Route as AuthenticatedProjectsIdSettingsMembersRouteImport } from './routes/_authenticated/projects/$id/settings/members';
import { Route as AuthenticatedProjectsIdIssuesIssueIdIndexRouteImport } from './routes/_authenticated/projects/$id/issues/$issueId/index';
import { Route as AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRouteImport } from './routes/_authenticated/projects/$id/issues/$issueId/events/$eventId';
import { Route as AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRouteImport } from './routes/_authenticated/projects/$id/issues/$issueId/events/empty';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const LinkAccountRoute = LinkAccountRouteImport.update({
  id: '/link-account',
  path: '/link-account',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsRetentionRoute =
  AuthenticatedSettingsRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsStorageRoute =
  AuthenticatedSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsTokensRoute =
  AuthenticatedSettingsTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedProjectsIdIndexRoute =
  AuthenticatedProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdLogsRoute =
  AuthenticatedProjectsIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdSettingsRoute =
  AuthenticatedProjectsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdAgentsIndexRoute =
  AuthenticatedProjectsIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdAgentsTraceIdRoute =
  AuthenticatedProjectsIdAgentsTraceIdRouteImport.update({
    id: '/agents/$traceId',
    path: '/agents/$traceId',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdIssuesIndexRoute =
  AuthenticatedProjectsIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdPerformanceIndexRoute =
  AuthenticatedProjectsIdPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdPerformanceTxnIdRoute =
  AuthenticatedProjectsIdPerformanceTxnIdRouteImport.update({
    id: '/performance/$txnId',
    path: '/performance/$txnId',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdPerformanceSummaryRoute =
  AuthenticatedProjectsIdPerformanceSummaryRouteImport.update({
    id: '/performance/summary',
    path: '/performance/summary',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdReleasesIndexRoute =
  AuthenticatedProjectsIdReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdReleasesReleaseRoute =
  AuthenticatedProjectsIdReleasesReleaseRouteImport.update({
    id: '/releases/$release',
    path: '/releases/$release',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdSettingsIndexRoute =
  AuthenticatedProjectsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsIdSettingsRoute,
  } as any);
const AuthenticatedProjectsIdSettingsAlertsRoute =
  AuthenticatedProjectsIdSettingsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedProjectsIdSettingsRoute,
  } as any);
const AuthenticatedProjectsIdSettingsClientKeysRoute =
  AuthenticatedProjectsIdSettingsClientKeysRouteImport.update({
    id: '/client-keys',
    path: '/client-keys',
    getParentRoute: () => AuthenticatedProjectsIdSettingsRoute,
  } as any);
const AuthenticatedProjectsIdSettingsGeneralRoute =
  AuthenticatedProjectsIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedProjectsIdSettingsRoute,
  } as any);
const AuthenticatedProjectsIdSettingsMembersRoute =
  AuthenticatedProjectsIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsIdSettingsRoute,
  } as any);
const AuthenticatedProjectsIdIssuesIssueIdIndexRoute =
  AuthenticatedProjectsIdIssuesIssueIdIndexRouteImport.update({
    id: '/issues/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute =
  AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRouteImport.update({
    id: '/issues/$issueId/events/$eventId',
    path: '/issues/$issueId/events/$eventId',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);
const AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute =
  AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRouteImport.update({
    id: '/issues/$issueId/events/empty',
    path: '/issues/$issueId/events/empty',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/link-account': typeof LinkAccountRoute;
  '/login': typeof LoginRoute;
  '/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/invite/$token': typeof InviteTokenRoute;
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren;
  '/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/settings/about': typeof AuthenticatedSettingsAboutRoute;
  '/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/retention': typeof AuthenticatedSettingsRetentionRoute;
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute;
  '/settings/team': typeof AuthenticatedSettingsTeamRoute;
  '/settings/tokens': typeof AuthenticatedSettingsTokensRoute;
  '/projects/': typeof AuthenticatedProjectsIndexRoute;
  '/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/projects/$id/logs': typeof AuthenticatedProjectsIdLogsRoute;
  '/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsRouteWithChildren;
  '/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute;
  '/projects/$id/agents/$traceId': typeof AuthenticatedProjectsIdAgentsTraceIdRoute;
  '/projects/$id/performance/$txnId': typeof AuthenticatedProjectsIdPerformanceTxnIdRoute;
  '/projects/$id/performance/summary': typeof AuthenticatedProjectsIdPerformanceSummaryRoute;
  '/projects/$id/releases/$release': typeof AuthenticatedProjectsIdReleasesReleaseRoute;
  '/projects/$id/settings/alerts': typeof AuthenticatedProjectsIdSettingsAlertsRoute;
  '/projects/$id/settings/client-keys': typeof AuthenticatedProjectsIdSettingsClientKeysRoute;
  '/projects/$id/settings/general': typeof AuthenticatedProjectsIdSettingsGeneralRoute;
  '/projects/$id/settings/members': typeof AuthenticatedProjectsIdSettingsMembersRoute;
  '/projects/$id/agents/': typeof AuthenticatedProjectsIdAgentsIndexRoute;
  '/projects/$id/issues/': typeof AuthenticatedProjectsIdIssuesIndexRoute;
  '/projects/$id/performance/': typeof AuthenticatedProjectsIdPerformanceIndexRoute;
  '/projects/$id/releases/': typeof AuthenticatedProjectsIdReleasesIndexRoute;
  '/projects/$id/settings/': typeof AuthenticatedProjectsIdSettingsIndexRoute;
  '/projects/$id/issues/$issueId/': typeof AuthenticatedProjectsIdIssuesIssueIdIndexRoute;
  '/projects/$id/issues/$issueId/events/$eventId': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute;
  '/projects/$id/issues/$issueId/events/empty': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/link-account': typeof LinkAccountRoute;
  '/login': typeof LoginRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/settings/about': typeof AuthenticatedSettingsAboutRoute;
  '/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/retention': typeof AuthenticatedSettingsRetentionRoute;
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute;
  '/settings/team': typeof AuthenticatedSettingsTeamRoute;
  '/settings/tokens': typeof AuthenticatedSettingsTokensRoute;
  '/projects': typeof AuthenticatedProjectsIndexRoute;
  '/settings': typeof AuthenticatedSettingsIndexRoute;
  '/projects/$id/logs': typeof AuthenticatedProjectsIdLogsRoute;
  '/projects/$id': typeof AuthenticatedProjectsIdIndexRoute;
  '/projects/$id/agents/$traceId': typeof AuthenticatedProjectsIdAgentsTraceIdRoute;
  '/projects/$id/performance/$txnId': typeof AuthenticatedProjectsIdPerformanceTxnIdRoute;
  '/projects/$id/performance/summary': typeof AuthenticatedProjectsIdPerformanceSummaryRoute;
  '/projects/$id/releases/$release': typeof AuthenticatedProjectsIdReleasesReleaseRoute;
  '/projects/$id/settings/alerts': typeof AuthenticatedProjectsIdSettingsAlertsRoute;
  '/projects/$id/settings/client-keys': typeof AuthenticatedProjectsIdSettingsClientKeysRoute;
  '/projects/$id/settings/general': typeof AuthenticatedProjectsIdSettingsGeneralRoute;
  '/projects/$id/settings/members': typeof AuthenticatedProjectsIdSettingsMembersRoute;
  '/projects/$id/agents': typeof AuthenticatedProjectsIdAgentsIndexRoute;
  '/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesIndexRoute;
  '/projects/$id/performance': typeof AuthenticatedProjectsIdPerformanceIndexRoute;
  '/projects/$id/releases': typeof AuthenticatedProjectsIdReleasesIndexRoute;
  '/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsIndexRoute;
  '/projects/$id/issues/$issueId': typeof AuthenticatedProjectsIdIssuesIssueIdIndexRoute;
  '/projects/$id/issues/$issueId/events/$eventId': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute;
  '/projects/$id/issues/$issueId/events/empty': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/link-account': typeof LinkAccountRoute;
  '/login': typeof LoginRoute;
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren;
  '/invite/$token': typeof InviteTokenRoute;
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren;
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute;
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute;
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/_authenticated/settings/retention': typeof AuthenticatedSettingsRetentionRoute;
  '/_authenticated/settings/storage': typeof AuthenticatedSettingsStorageRoute;
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute;
  '/_authenticated/settings/tokens': typeof AuthenticatedSettingsTokensRoute;
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute;
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/_authenticated/projects/$id/logs': typeof AuthenticatedProjectsIdLogsRoute;
  '/_authenticated/projects/$id/settings': typeof AuthenticatedProjectsIdSettingsRouteWithChildren;
  '/_authenticated/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute;
  '/_authenticated/projects/$id/agents/$traceId': typeof AuthenticatedProjectsIdAgentsTraceIdRoute;
  '/_authenticated/projects/$id/performance/$txnId': typeof AuthenticatedProjectsIdPerformanceTxnIdRoute;
  '/_authenticated/projects/$id/performance/summary': typeof AuthenticatedProjectsIdPerformanceSummaryRoute;
  '/_authenticated/projects/$id/releases/$release': typeof AuthenticatedProjectsIdReleasesReleaseRoute;
  '/_authenticated/projects/$id/settings/alerts': typeof AuthenticatedProjectsIdSettingsAlertsRoute;
  '/_authenticated/projects/$id/settings/client-keys': typeof AuthenticatedProjectsIdSettingsClientKeysRoute;
  '/_authenticated/projects/$id/settings/general': typeof AuthenticatedProjectsIdSettingsGeneralRoute;
  '/_authenticated/projects/$id/settings/members': typeof AuthenticatedProjectsIdSettingsMembersRoute;
  '/_authenticated/projects/$id/agents/': typeof AuthenticatedProjectsIdAgentsIndexRoute;
  '/_authenticated/projects/$id/issues/': typeof AuthenticatedProjectsIdIssuesIndexRoute;
  '/_authenticated/projects/$id/performance/': typeof AuthenticatedProjectsIdPerformanceIndexRoute;
  '/_authenticated/projects/$id/releases/': typeof AuthenticatedProjectsIdReleasesIndexRoute;
  '/_authenticated/projects/$id/settings/': typeof AuthenticatedProjectsIdSettingsIndexRoute;
  '/_authenticated/projects/$id/issues/$issueId/': typeof AuthenticatedProjectsIdIssuesIssueIdIndexRoute;
  '/_authenticated/projects/$id/issues/$issueId/events/$eventId': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute;
  '/_authenticated/projects/$id/issues/$issueId/events/empty': typeof AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/link-account'
    | '/login'
    | '/settings'
    | '/invite/$token'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/retention'
    | '/settings/storage'
    | '/settings/team'
    | '/settings/tokens'
    | '/projects/'
    | '/settings/'
    | '/projects/$id/logs'
    | '/projects/$id/settings'
    | '/projects/$id/'
    | '/projects/$id/agents/$traceId'
    | '/projects/$id/performance/$txnId'
    | '/projects/$id/performance/summary'
    | '/projects/$id/releases/$release'
    | '/projects/$id/settings/alerts'
    | '/projects/$id/settings/client-keys'
    | '/projects/$id/settings/general'
    | '/projects/$id/settings/members'
    | '/projects/$id/agents/'
    | '/projects/$id/issues/'
    | '/projects/$id/performance/'
    | '/projects/$id/releases/'
    | '/projects/$id/settings/'
    | '/projects/$id/issues/$issueId/'
    | '/projects/$id/issues/$issueId/events/$eventId'
    | '/projects/$id/issues/$issueId/events/empty';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/link-account'
    | '/login'
    | '/invite/$token'
    | '/projects/new'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/retention'
    | '/settings/storage'
    | '/settings/team'
    | '/settings/tokens'
    | '/projects'
    | '/settings'
    | '/projects/$id/logs'
    | '/projects/$id'
    | '/projects/$id/agents/$traceId'
    | '/projects/$id/performance/$txnId'
    | '/projects/$id/performance/summary'
    | '/projects/$id/releases/$release'
    | '/projects/$id/settings/alerts'
    | '/projects/$id/settings/client-keys'
    | '/projects/$id/settings/general'
    | '/projects/$id/settings/members'
    | '/projects/$id/agents'
    | '/projects/$id/issues'
    | '/projects/$id/performance'
    | '/projects/$id/releases'
    | '/projects/$id/settings'
    | '/projects/$id/issues/$issueId'
    | '/projects/$id/issues/$issueId/events/$eventId'
    | '/projects/$id/issues/$issueId/events/empty';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/link-account'
    | '/login'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/retention'
    | '/_authenticated/settings/storage'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/tokens'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/projects/$id/logs'
    | '/_authenticated/projects/$id/settings'
    | '/_authenticated/projects/$id/'
    | '/_authenticated/projects/$id/agents/$traceId'
    | '/_authenticated/projects/$id/performance/$txnId'
    | '/_authenticated/projects/$id/performance/summary'
    | '/_authenticated/projects/$id/releases/$release'
    | '/_authenticated/projects/$id/settings/alerts'
    | '/_authenticated/projects/$id/settings/client-keys'
    | '/_authenticated/projects/$id/settings/general'
    | '/_authenticated/projects/$id/settings/members'
    | '/_authenticated/projects/$id/agents/'
    | '/_authenticated/projects/$id/issues/'
    | '/_authenticated/projects/$id/performance/'
    | '/_authenticated/projects/$id/releases/'
    | '/_authenticated/projects/$id/settings/'
    | '/_authenticated/projects/$id/issues/$issueId/'
    | '/_authenticated/projects/$id/issues/$issueId/events/$eventId'
    | '/_authenticated/projects/$id/issues/$issueId/events/empty';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LinkAccountRoute: typeof LinkAccountRoute;
  LoginRoute: typeof LoginRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/link-account': {
      id: '/link-account';
      path: '/link-account';
      fullPath: '/link-account';
      preLoaderRoute: typeof LinkAccountRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/settings': {
      id: '/_authenticated/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/invite/$token': {
      id: '/invite/$token';
      path: '/invite/$token';
      fullPath: '/invite/$token';
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/';
      path: '/projects';
      fullPath: '/projects/';
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id';
      path: '/projects/$id';
      fullPath: '/projects/$id';
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new';
      path: '/projects/new';
      fullPath: '/projects/new';
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about';
      path: '/about';
      fullPath: '/settings/about';
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account';
      path: '/account';
      fullPath: '/settings/account';
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance';
      path: '/appearance';
      fullPath: '/settings/appearance';
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations';
      path: '/integrations';
      fullPath: '/settings/integrations';
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/retention': {
      id: '/_authenticated/settings/retention';
      path: '/retention';
      fullPath: '/settings/retention';
      preLoaderRoute: typeof AuthenticatedSettingsRetentionRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/storage': {
      id: '/_authenticated/settings/storage';
      path: '/storage';
      fullPath: '/settings/storage';
      preLoaderRoute: typeof AuthenticatedSettingsStorageRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team';
      path: '/team';
      fullPath: '/settings/team';
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/settings/tokens': {
      id: '/_authenticated/settings/tokens';
      path: '/tokens';
      fullPath: '/settings/tokens';
      preLoaderRoute: typeof AuthenticatedSettingsTokensRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    '/_authenticated/projects/$id/': {
      id: '/_authenticated/projects/$id/';
      path: '/';
      fullPath: '/projects/$id/';
      preLoaderRoute: typeof AuthenticatedProjectsIdIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/logs': {
      id: '/_authenticated/projects/$id/logs';
      path: '/logs';
      fullPath: '/projects/$id/logs';
      preLoaderRoute: typeof AuthenticatedProjectsIdLogsRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/settings': {
      id: '/_authenticated/projects/$id/settings';
      path: '/settings';
      fullPath: '/projects/$id/settings';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/agents/': {
      id: '/_authenticated/projects/$id/agents/';
      path: '/agents';
      fullPath: '/projects/$id/agents/';
      preLoaderRoute: typeof AuthenticatedProjectsIdAgentsIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/agents/$traceId': {
      id: '/_authenticated/projects/$id/agents/$traceId';
      path: '/agents/$traceId';
      fullPath: '/projects/$id/agents/$traceId';
      preLoaderRoute: typeof AuthenticatedProjectsIdAgentsTraceIdRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/issues/': {
      id: '/_authenticated/projects/$id/issues/';
      path: '/issues';
      fullPath: '/projects/$id/issues/';
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/performance/': {
      id: '/_authenticated/projects/$id/performance/';
      path: '/performance';
      fullPath: '/projects/$id/performance/';
      preLoaderRoute: typeof AuthenticatedProjectsIdPerformanceIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/performance/$txnId': {
      id: '/_authenticated/projects/$id/performance/$txnId';
      path: '/performance/$txnId';
      fullPath: '/projects/$id/performance/$txnId';
      preLoaderRoute: typeof AuthenticatedProjectsIdPerformanceTxnIdRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/performance/summary': {
      id: '/_authenticated/projects/$id/performance/summary';
      path: '/performance/summary';
      fullPath: '/projects/$id/performance/summary';
      preLoaderRoute: typeof AuthenticatedProjectsIdPerformanceSummaryRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/releases/': {
      id: '/_authenticated/projects/$id/releases/';
      path: '/releases';
      fullPath: '/projects/$id/releases/';
      preLoaderRoute: typeof AuthenticatedProjectsIdReleasesIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/releases/$release': {
      id: '/_authenticated/projects/$id/releases/$release';
      path: '/releases/$release';
      fullPath: '/projects/$id/releases/$release';
      preLoaderRoute: typeof AuthenticatedProjectsIdReleasesReleaseRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/settings/': {
      id: '/_authenticated/projects/$id/settings/';
      path: '/';
      fullPath: '/projects/$id/settings/';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdSettingsRoute;
    };
    '/_authenticated/projects/$id/settings/alerts': {
      id: '/_authenticated/projects/$id/settings/alerts';
      path: '/alerts';
      fullPath: '/projects/$id/settings/alerts';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsAlertsRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdSettingsRoute;
    };
    '/_authenticated/projects/$id/settings/client-keys': {
      id: '/_authenticated/projects/$id/settings/client-keys';
      path: '/client-keys';
      fullPath: '/projects/$id/settings/client-keys';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsClientKeysRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdSettingsRoute;
    };
    '/_authenticated/projects/$id/settings/general': {
      id: '/_authenticated/projects/$id/settings/general';
      path: '/general';
      fullPath: '/projects/$id/settings/general';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsGeneralRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdSettingsRoute;
    };
    '/_authenticated/projects/$id/settings/members': {
      id: '/_authenticated/projects/$id/settings/members';
      path: '/members';
      fullPath: '/projects/$id/settings/members';
      preLoaderRoute: typeof AuthenticatedProjectsIdSettingsMembersRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdSettingsRoute;
    };
    '/_authenticated/projects/$id/issues/$issueId/': {
      id: '/_authenticated/projects/$id/issues/$issueId/';
      path: '/issues/$issueId';
      fullPath: '/projects/$id/issues/$issueId/';
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesIssueIdIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/issues/$issueId/events/$eventId': {
      id: '/_authenticated/projects/$id/issues/$issueId/events/$eventId';
      path: '/issues/$issueId/events/$eventId';
      fullPath: '/projects/$id/issues/$issueId/events/$eventId';
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
    '/_authenticated/projects/$id/issues/$issueId/events/empty': {
      id: '/_authenticated/projects/$id/issues/$issueId/events/empty';
      path: '/issues/$issueId/events/empty';
      fullPath: '/projects/$id/issues/$issueId/events/empty';
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRouteImport;
      parentRoute: typeof AuthenticatedProjectsIdRoute;
    };
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute;
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute;
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute;
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute;
  AuthenticatedSettingsRetentionRoute: typeof AuthenticatedSettingsRetentionRoute;
  AuthenticatedSettingsStorageRoute: typeof AuthenticatedSettingsStorageRoute;
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute;
  AuthenticatedSettingsTokensRoute: typeof AuthenticatedSettingsTokensRoute;
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsRetentionRoute: AuthenticatedSettingsRetentionRoute,
  AuthenticatedSettingsStorageRoute: AuthenticatedSettingsStorageRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsTokensRoute: AuthenticatedSettingsTokensRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
};

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  );

interface AuthenticatedProjectsIdSettingsRouteChildren {
  AuthenticatedProjectsIdSettingsAlertsRoute: typeof AuthenticatedProjectsIdSettingsAlertsRoute;
  AuthenticatedProjectsIdSettingsClientKeysRoute: typeof AuthenticatedProjectsIdSettingsClientKeysRoute;
  AuthenticatedProjectsIdSettingsGeneralRoute: typeof AuthenticatedProjectsIdSettingsGeneralRoute;
  AuthenticatedProjectsIdSettingsMembersRoute: typeof AuthenticatedProjectsIdSettingsMembersRoute;
  AuthenticatedProjectsIdSettingsIndexRoute: typeof AuthenticatedProjectsIdSettingsIndexRoute;
}

const AuthenticatedProjectsIdSettingsRouteChildren: AuthenticatedProjectsIdSettingsRouteChildren =
  {
    AuthenticatedProjectsIdSettingsAlertsRoute:
      AuthenticatedProjectsIdSettingsAlertsRoute,
    AuthenticatedProjectsIdSettingsClientKeysRoute:
      AuthenticatedProjectsIdSettingsClientKeysRoute,
    AuthenticatedProjectsIdSettingsGeneralRoute:
      AuthenticatedProjectsIdSettingsGeneralRoute,
    AuthenticatedProjectsIdSettingsMembersRoute:
      AuthenticatedProjectsIdSettingsMembersRoute,
    AuthenticatedProjectsIdSettingsIndexRoute:
      AuthenticatedProjectsIdSettingsIndexRoute,
  };

const AuthenticatedProjectsIdSettingsRouteWithChildren =
  AuthenticatedProjectsIdSettingsRoute._addFileChildren(
    AuthenticatedProjectsIdSettingsRouteChildren,
  );

interface AuthenticatedProjectsIdRouteChildren {
  AuthenticatedProjectsIdLogsRoute: typeof AuthenticatedProjectsIdLogsRoute;
  AuthenticatedProjectsIdSettingsRoute: typeof AuthenticatedProjectsIdSettingsRouteWithChildren;
  AuthenticatedProjectsIdIndexRoute: typeof AuthenticatedProjectsIdIndexRoute;
  AuthenticatedProjectsIdAgentsTraceIdRoute: typeof AuthenticatedProjectsIdAgentsTraceIdRoute;
  AuthenticatedProjectsIdPerformanceTxnIdRoute: typeof AuthenticatedProjectsIdPerformanceTxnIdRoute;
  AuthenticatedProjectsIdPerformanceSummaryRoute: typeof AuthenticatedProjectsIdPerformanceSummaryRoute;
  AuthenticatedProjectsIdReleasesReleaseRoute: typeof AuthenticatedProjectsIdReleasesReleaseRoute;
  AuthenticatedProjectsIdAgentsIndexRoute: typeof AuthenticatedProjectsIdAgentsIndexRoute;
  AuthenticatedProjectsIdIssuesIndexRoute: typeof AuthenticatedProjectsIdIssuesIndexRoute;
  AuthenticatedProjectsIdPerformanceIndexRoute: typeof AuthenticatedProjectsIdPerformanceIndexRoute;
  AuthenticatedProjectsIdReleasesIndexRoute: typeof AuthenticatedProjectsIdReleasesIndexRoute;
  AuthenticatedProjectsIdIssuesIssueIdIndexRoute: typeof AuthenticatedProjectsIdIssuesIssueIdIndexRoute;
  AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute: typeof AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute;
  AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute: typeof AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute;
}

const AuthenticatedProjectsIdRouteChildren: AuthenticatedProjectsIdRouteChildren =
  {
    AuthenticatedProjectsIdLogsRoute: AuthenticatedProjectsIdLogsRoute,
    AuthenticatedProjectsIdSettingsRoute:
      AuthenticatedProjectsIdSettingsRouteWithChildren,
    AuthenticatedProjectsIdIndexRoute: AuthenticatedProjectsIdIndexRoute,
    AuthenticatedProjectsIdAgentsTraceIdRoute:
      AuthenticatedProjectsIdAgentsTraceIdRoute,
    AuthenticatedProjectsIdPerformanceTxnIdRoute:
      AuthenticatedProjectsIdPerformanceTxnIdRoute,
    AuthenticatedProjectsIdPerformanceSummaryRoute:
      AuthenticatedProjectsIdPerformanceSummaryRoute,
    AuthenticatedProjectsIdReleasesReleaseRoute:
      AuthenticatedProjectsIdReleasesReleaseRoute,
    AuthenticatedProjectsIdAgentsIndexRoute:
      AuthenticatedProjectsIdAgentsIndexRoute,
    AuthenticatedProjectsIdIssuesIndexRoute:
      AuthenticatedProjectsIdIssuesIndexRoute,
    AuthenticatedProjectsIdPerformanceIndexRoute:
      AuthenticatedProjectsIdPerformanceIndexRoute,
    AuthenticatedProjectsIdReleasesIndexRoute:
      AuthenticatedProjectsIdReleasesIndexRoute,
    AuthenticatedProjectsIdIssuesIssueIdIndexRoute:
      AuthenticatedProjectsIdIssuesIssueIdIndexRoute,
    AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute:
      AuthenticatedProjectsIdIssuesIssueIdEventsEventIdRoute,
    AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute:
      AuthenticatedProjectsIdIssuesIssueIdEventsEmptyRoute,
  };

const AuthenticatedProjectsIdRouteWithChildren =
  AuthenticatedProjectsIdRoute._addFileChildren(
    AuthenticatedProjectsIdRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren;
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRouteWithChildren;
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute;
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LinkAccountRoute: LinkAccountRoute,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
